// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PacotedetestesdocadastrodoalunoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT01REQ03CadastrarAlunocomsucesso() {
    driver.get("https://scel.herokuapp.com/sig/aluno");
    driver.manage().window().setSize(new Dimension(896, 770));
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("2031");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Fulano");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("fulano@hotmail.com");
    driver.findElement(By.id("cep")).click();
    driver.findElement(By.id("cep")).sendKeys("03694000");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }
  @Test
  public void cT02REQ03CadastrarAlunocomrainvalido() {
    driver.get("https://scel.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(896, 770));
    driver.findElement(By.cssSelector("li:nth-child(2) font > font")).click();
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("1");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Fulano");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("fulano@hotmail.com");
    driver.findElement(By.id("cep")).click();
    driver.findElement(By.id("cep")).sendKeys("03694000");
  }
  @Test
  public void cT03REQ03CadastrarAlunocomnomeinvalido() {
    driver.get("https://scel.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(896, 770));
    driver.findElement(By.cssSelector("li:nth-child(2) font > font")).click();
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("2031");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("fulano@hotmail.com");
    driver.findElement(By.id("cep")).click();
    driver.findElement(By.id("cep")).sendKeys("03694000");
  }
  @Test
  public void cT04REQ03CadastrarAlunocomemailinvalido() {
    driver.get("https://scel.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(896, 770));
    driver.findElement(By.linkText("Alunos")).click();
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("2031");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Fulano");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("Fulano*hotmail");
    driver.findElement(By.id("cep")).click();
    driver.findElement(By.id("cep")).sendKeys("03694000");
  }
  @Test
  public void cT05REQ03CadastrarAlunocomcepinvalido() {
    driver.get("https://scel.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(896, 770));
    driver.findElement(By.cssSelector("li:nth-child(2) font > font")).click();
    driver.findElement(By.id("ra")).click();
    driver.findElement(By.id("ra")).sendKeys("2031");
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Fulano");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("fulano@hotmail.com");
    driver.findElement(By.id("cep")).click();
    driver.findElement(By.id("cep")).sendKeys("038");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }
}
